# Generated by Django 6.0.4 on 2026-05-11 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('partenaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_operation', to='catalogue.produit')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.operationstock')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RETOUR ENTREE', 'Retour fournisseur'), ('RETOUR SORTIE', 'Retour client')], max_length=15)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('ligne_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mouvement', to='stock.ligneoperation')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='catalogue.produit')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stock.operationstock')),
            ],
        ),
        migrations.CreateModel(
            name='OperationStockEntree',
            fields=[
                ('operationstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.operationstock')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Entree_stock', to='partenaires.fournisseur')),
            ],
            bases=('stock.operationstock',),
        ),
        migrations.CreateModel(
            name='OperationStockSortie',
            fields=[
                ('operationstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.operationstock')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sortie_stock', to='partenaires.client')),
            ],
            bases=('stock.operationstock',),
        ),
    ]
