# Generated by Django 6.0.5 on 2026-05-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligneoperation',
            options={'verbose_name': "Ligne d'opération", 'verbose_name_plural': "Lignes d'opération"},
        ),
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='operationstock',
            options={'verbose_name': 'Opération de stock', 'verbose_name_plural': 'Opérations de stock'},
        ),
        migrations.AlterModelOptions(
            name='operationstockentree',
            options={'verbose_name': 'Entrée de stock', 'verbose_name_plural': 'Entrées de stock'},
        ),
        migrations.AlterModelOptions(
            name='operationstocksortie',
            options={'verbose_name': 'Sortie de stock', 'verbose_name_plural': 'Sorties de stock'},
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=15),
        ),
        migrations.AlterField(
            model_name='operationstockentree',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrees_stock', to='partenaires.fournisseur'),
        ),
        migrations.AlterField(
            model_name='operationstocksortie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sorties_stock', to='partenaires.client'),
        ),
    ]
