# Generated by Django 6.0.5 on 2026-05-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
        ('stock', '0002_alter_ligneoperation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligneoperation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operationstock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operationstockentree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operationstocksortie',
            options={},
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RETOUR ENTREE', 'Retour fournisseur'), ('RETOUR SORTIE', 'Retour client')], max_length=15),
        ),
        migrations.AlterField(
            model_name='operationstockentree',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Entree_stock', to='partenaires.fournisseur'),
        ),
        migrations.AlterField(
            model_name='operationstocksortie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sortie_stock', to='partenaires.client'),
        ),
    ]
