# Generated by Django 6.0.4 on 2026-05-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_ligneoperation_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligneoperation',
            old_name='prix',
            new_name='prix_total',
        ),
    ]
