# Generated by Django 6.0.4 on 2026-05-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_prix_ligneoperation_prix_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneoperation',
            name='prix_total',
        ),
    ]
