# Generated by Django 6.0.4 on 2026-05-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
        ('stock', '0004_remove_ligneoperation_prix_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationstock',
            name='client',
        ),
        migrations.RemoveField(
            model_name='operationstock',
            name='type_operation',
        ),
        migrations.CreateModel(
            name='OperationStockEntree',
            fields=[
                ('operationstock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.operationstock')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_stock', to='partenaires.fournisseur')),
            ],
            bases=('stock.operationstock',),
        ),
        migrations.CreateModel(
            name='OperationStockSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_stock', to='partenaires.client')),
            ],
        ),
    ]
