# Generated by Django 6.0.4 on 2026-05-07 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partenaires', '0001_initial'),
        ('stock', '0005_remove_operationstock_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationstocksortie',
            name='id',
        ),
        migrations.AddField(
            model_name='operationstocksortie',
            name='operationstock_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stock.operationstock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationstockentree',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Entree_stock', to='partenaires.fournisseur'),
        ),
        migrations.AlterField(
            model_name='operationstocksortie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sortie_stock', to='partenaires.client'),
        ),
    ]
