# Generated by Django 6.0.4 on 2026-05-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_operationstocksortie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementstock',
            name='quantite',
        ),
    ]
