# Generated by Django 6.0.4 on 2026-05-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_mouvementstock_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RETOUR ENTREE', 'Retour fournisseur'), ('RETOUR SORTIE', 'Retour client')], max_length=15),
        ),
    ]
