# Generated by Django 6.0.4 on 2026-05-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
    ]
