# Generated by Django 6.0.4 on 2026-05-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
