# Generated by Django 6.0.4 on 2026-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_produit_seuil_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
